@echo off
rem This file was generated by the Jython installer
rem Created on Tue May 20 12:44:08 EDT 2008 by Owner

set ARGS=

:loop
if [%1] == [] goto end
    set ARGS=%ARGS% %1
    shift
    goto loop
:end

"C:\Program Files\Java\jre1.6.0_04\bin\java.exe" -Dpython.home="C:\jes-3-1-windows\jes\jython-2.2.1" -classpath "C:\jes-3-1-windows\jes\jython-2.2.1\jython.jar;%CLASSPATH%" org.python.util.jython %ARGS%
